### ISSUE TITLE
DEVELOPER_DIR is not set for usage with fastlane

### ISSUE THREAD

**Issue by dentuzhik** [maxim-lobanov/setup-xcode#13]
Recently we have had some issues when using this action with `fastlane`, that our lanes have still been using wrong versions of Xcode, even after version is being set.

Fastlane itself recommends either to use `xcode-select` (which this action does) or set `DEVELOPER_DIR`.
https://docs.fastlane.tools/actions/gym/#usage

Currently we are solving it in a bit hackish way and use `MD_APPLE_SDK_ROOT` set for Xamarin.
```yaml
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 11.7

      - name: Build Simulator build
        timeout-minutes: 15
        env:
          # N.B. Unless we set this, fastlane will still use default Xcode available on the machine
          DEVELOPER_DIR: ${{ env.MD_APPLE_SDK_ROOT }}
        run: |
          bundle exec fastlane ios build_simulator 
```

Considering that `xcode-select` is actually used, alternative version woudl be to use:
```
DEVELOPER_DIR: $(xcode-select --print-path)
``` 

But I was wondering, considering how often fastlane used for iOS, would you consider adding this or accepting the PR, which sets `DEVELOPER_DIR` as a part of workflow? Or should we consider some other solutin?

Thanks in advance.
