### ISSUE TITLE
latest-stable is selecting beta 12.5

### ISSUE THREAD

**Issue by yuri-qualtie** [maxim-lobanov/setup-xcode#20]
We are expecting action to select 12.4 but we are getting 12.5:

```
Switching Xcode to version 'latest-stable'...
Xcode is set to 12.5.0 (12E262)
```

12.4 is both the latest version that appears in the App Store and the latest stable version that appears in the [virtual-environments repo](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode)

We tried both 1.2.1 and 1.2.2 but they produce same result.

Our setup:
```
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.2.2
      with:
        xcode-version: latest-stable
```
