### ISSUE TITLE
Support for Xcode 13

### ISSUE THREAD

**Issue by ygit** [maxim-lobanov/setup-xcode#36]
@maxim-lobanov  When is support for Xcode 13 coming?

**Comment by maxim-lobanov** [comment]
Hello @ygit , Xcode 13 is supported for a long time already.
This action don't need to be updated everytime when new Xcode is released. It just selects between Xcode versions installed on Hosted images.

Readme of this repo contains example:
```
jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
```
