### ISSUE TITLE
Wrong Xcode version being selected

### ISSUE THREAD

**Issue by atrinh0** [maxim-lobanov/setup-xcode#46]
Context:
On GitHub Actions, the following Xcode versions are available:

https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xcode

Version | Build | Path
-- | -- | --
14.1 (beta) | 14B5024h | /Applications/Xcode_14.1.app
14.0.1 | 14A400 | /Applications/Xcode_14.0.1.app
14.0 | 14A309 | /Applications/Xcode_14.0.app

Setting the workflow file to the following:

```
    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: 14.0
```

Results in the following:

<img width="401" alt="Screenshot 2022-09-20 at 11 23 28" src="https://user-images.githubusercontent.com/16542463/191233999-65ff9eda-2d28-4d10-a1fd-0d1635be02ee.png">

**Comment by atrinh0** [comment]
I noticed the version used is 2 years behind, will update to the latest to verify.

**Comment by atrinh0** [comment]
The latest tagged version select Xcode `14.0.1` instead of `14.0` (as defined in the workflow file).

<img width="400" alt="Screenshot 2022-09-20 at 11 33 08" src="https://user-images.githubusercontent.com/16542463/191235968-2ad68f83-b087-4c12-87af-d723ddf1250b.png">

**Comment by atrinh0** [comment]
After reading the documentation the workflow file was adjusted to wrap the version in single quotes:

```
steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: '14.0'
```

Which produces the following results:

<img width="390" alt="Screenshot 2022-09-20 at 11 39 02" src="https://user-images.githubusercontent.com/16542463/191237035-81b2d563-dbfd-4cd5-bd53-b410b4e3793f.png">
