### ISSUE TITLE
Update & support Xcode version 14.1

### ISSUE THREAD

**Issue by anatoliykant** [maxim-lobanov/setup-xcode#59]
Thx for the great action.
Could you please update it and support Xcode version 14.1?

**Comment by maxim-lobanov** [comment]
Hey @anatoliykant , 
What exact problem do you have with using Xcode 14.1?
This action is not required any manual adaptation for new Xcode versions and just consume Xcode versions which GitHub Actions provide on images.

If you use `macos-12` image, Xcode 14.1 should be available on it.
See this example:
```yaml
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 14.1
```

You can use either `14.1` or `latest-stable` in `xcode-version` input on macOS 12 image to get Xcode 14.1
