### ISSUE TITLE
macOS-13 support

### ISSUE THREAD

**Issue by salvatoreboemia** [maxim-lobanov/setup-xcode#67]
Hi is available the macos 13 support with new xcode 15?

thanks

**Comment by maxim-lobanov** [comment]
Hi, This actions should work with all macOS images and all xcode versions which are pre-installed on GitHub Hosted images.
As I can see only Xcode 15 beta is pre-installed right now: https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode

I think GitHub Actions team is going to deploy new image with Xcode 15 stable within a couple of days. As soon as it is deployed, this doc will be updated.
After that, this action will work automatically with new version.

**Comment by kenji21** [comment]
it has been deployed: https://github.com/actions/runner-images/issues/8282#issuecomment-1733633274

**Comment by kenji21** [comment]
Find a simpler way, in `.github/actions/configure_xcode_version/action.yaml`:

```
name: "Configure: Xcode version"

runs:
  using: "composite"
  steps:
    - name: "Configure: Xcode version"
      shell: bash
      # for Xcode path, see https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
      run: echo "DEVELOPER_DIR=/Applications/Xcode_15.0.app" >> $GITHUB_ENV
```
