### ISSUE TITLE
Using "runs-on: macos-13-xlarge" leads to inconsistencies

### ISSUE THREAD

**Issue by piofusco** [maxim-lobanov/setup-xcode#71]
Inconsistently seeing the following when trying to run any of my related workflows:

![image](https://github.com/maxim-lobanov/setup-xcode/assets/6620352/2080b0fa-ac26-4f42-b553-f594a15f3b76)

For more context, here's what most of our workflows look like
```
name: Continuous Integration
on: pull_request
concurrency:
  group: ${{ github.head_ref }}-unit-tests
  cancel-in-progress: true
jobs:
  unit-tests:
    runs-on: macos-13-xlarge
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore SPM Cache
        uses: actions/cache@v3
        with:
          path: SPMCache
          key: ${{ runner.os }}-spm-reduced-cache-${{ hashFiles('**/packages.yml') }}
          restore-keys: ${{ runner.os }}-spm-reduced-cache-
      - name: Xcode Configuration
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - name: Install Xcodegen
        run: brew install xcodegen
      - name: Generate project
        run: xcodegen generate
      - name: Run Unit Tests
        run: bundle exec fastlane unit_tests
        env:
          CI: true
          HAS_PACKAGES_CACHE_HIT: ${{ steps.packages-cache.outputs.cache-hit == 'true' }}
```

While I imagine this might be related to [this Github actions issue](https://github.com/actions/runner-images/issues/8697), I figured it couldn't hurt to be sure I am not missing something.
