### ISSUE TITLE
Xcode and xcodebuild versions are not matching

### ISSUE THREAD

**Issue by kstoletniy** [maxim-lobanov/setup-xcode#75]
A few weeks ago, the workflow utilizing the macOS-13 runner unexpectedly began to fail. Prior to this, the workflow was functioning correctly, and no modifications were made to the workflow file. The failure stemmed from the fact that the Swift tool version was outdated compared to the one utilized in my project's packages. In my local project, I employ Xcode 15.2, so I specified '15.2-beta' in the workflow.

After an extensive investigation into the potential cause of the issue, I discovered that xcodebuild was pointing to version 14.3.1, leading to the problems encountered.

Three weeks ago, everything was functioning smoothly, and both the Xcode version and xcodebuild matched seamlessly. It appears that an issue was introduced recently, causing the discrepancy.

I urgently request assistance in resolving this matter as it is impeding all of my workflows.

**Image version and build link**
Version: 20240106.8
Included Software: https://github.com/actions/runner-images/blob/macos-13/20240106.8/images/macos/macos-13-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20240106.8

**Expected behavior**
The xcode version and xcodebuild version should match always. i.e.
<img width="1057" alt="Screenshot 2024-01-15 at 10 31 58" src="https://github.com/maxim-lobanov/setup-xcode/assets/79856619/b1b27e04-8ef5-464c-872b-b95baa9e4ab8">

**Actual behavior**
The xcode version and xcodebuild version are not matching versions.
<img width="1057" alt="Screenshot 2024-01-15 at 10 26 32" src="https://github.com/maxim-lobanov/setup-xcode/assets/79856619/d736e5c3-fcde-4f6a-b727-de4520aed2ac">

**Comment by maxim-lobanov** [comment]
Hey 👋 
We didn't have any updated to this action from Sep 2023. So if workflow started to fail without changes on your side, most likely it is related to image and worth to be reported to https://github.com/actions/runner-images repo.

Could you please confirm that issue is still reproduced for you?
I can't repro it using the following workflow file:
```yaml
jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2-beta'
    - run: |
        xcode-select -print-path
    - run: |
        xcodebuild -version
```

I wonder if something on image side is changed again and fixed it 🤔 

If it is still reproduced for you, could you run the same workflow in your repo (with `xcode-select -print-path` step and share logs)

**Comment by sisoje** [comment]
why not set the explicit version that user wants? I could not set 16.0.0

**Comment by jeffremer** [comment]
Just ran into this. It's likely been failing silently for a while since we're only now bumping up from 15.1 to 15.4.

On our self-hosted runners, the workflow:

```
name: xcode-select
description: Uses .xcode-version to set the Xcode version
runs:
  using: "composite"
  steps:
    - id: version
      shell: sh
      run: |
        version=$(cat .xcode-version)
        echo "Setting Xcode version to: $version"
        echo "xcode-version=$version" >> $GITHUB_OUTPUT
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ steps.version.outputs.xcode-version }}
    - name: Print Xcode version
      shell: sh
      run: |
        xcode-select -print-path
        xcodebuild -version
        swift -version
```

Example output:

![Screenshot 2024-08-02 at 6 19 08 PM](https://github.com/user-attachments/assets/125166d1-b1e8-4e23-b0d4-85a298f4e101)

I'm guessing the GitHub actions runners allowed sudoers or something similar, but that's not the default so our self-hosted runners have been failing silently. It'd be nice at least if the action errored out in that case.
