### ISSUE TITLE
 Could not find Xcode version that satisfied version spec: '15.2'

### ISSUE THREAD

**Issue by marcofugaro** [maxim-lobanov/setup-xcode#76]
Looks like this action doesn't work with relatively new XCode versions. This is my setup:

```yml
- uses: maxim-lobanov/setup-xcode@v1
     with:
       xcode-version: '15.2'
```

Error:

<img width="924" alt="image" src="https://github.com/maxim-lobanov/setup-xcode/assets/7217420/3803a5b8-da0b-43d2-ae71-e446ccf1198c">
