### ISSUE TITLE
xcode-version 12.0 points to Xcode 12.2 beta

### ISSUE THREAD

**Issue by JonnyBeeGod** [maxim-lobanov/setup-xcode#8]
I am using the following configuration: 

```
steps:
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.0

```
This leads to the action using Xcode 12.2:
<img width="391" alt="Bildschirmfoto 2020-10-04 um 16 27 34" src="https://user-images.githubusercontent.com/2844335/95018222-8e5bb780-065e-11eb-954c-23caa00f0083.png">

This is wrong as I expect the action using Xcode 12.0 as specified. 

Workaround: latest-stable does use Xcode 12.0 as expected
