### ISSUE TITLE
iOS 18.2 doesn't get installed

### ISSUE THREAD

**Issue by Tobi696** [maxim-lobanov/setup-xcode#90]
I use this step with the following configuration in my workflow:
![Screenshot 2025-01-09 at 10 23 49](https://github.com/user-attachments/assets/2ea33ca2-ab40-42b2-b081-84331cb4eab6)

It worked until iOS 16.2 became available, now I get this error:
![Screenshot 2025-01-09 at 10 24 29](https://github.com/user-attachments/assets/ca7a48c0-72a9-426f-8594-475cb8c82ad9)

**Comment by lthoedt** [comment]
Same. Installing it manually does work but that sucks.

**Comment by Tobi696** [comment]
@lthoedt How do you install manually?

**Comment by lthoedt** [comment]
> @lthoedt How do you install manually?

```
xcodebuild -downloadPlatform iOS -buildVersion 18.2 -exportPath ~/SimulatorRuntimes/
xcodebuild -importPlatform "/Users/runner/SimulatorRuntimes/iphonesimulator_18.2_22C150.dmg"
```

This works but is quite fragile. You could improve this by extracting the path from the output of the first command.
This is like 8Gb so that sucks to download each time, cache only allows a total of 10Gb so that would leave only 2Gb for other caches.

**Comment by aksh1t** [comment]
+1 Bumping this. Getting the same error as well. I've temporarily reverted to using `Xcode 16.1` as a workaround.

**Comment by shivankacker** [comment]
+1, can we get a fix for this?

**Comment by shivankacker** [comment]
Updating Actions runner to `macos-15` solved it for me.

**Comment by laurentcabondm** [comment]
Hello. Do we have any updates on this issue? Thanks

**Comment by GuilhE** [comment]
> > [@lthoedt](https://github.com/lthoedt) How do you install manually?
> 
> ```
> xcodebuild -downloadPlatform iOS -buildVersion 18.2 -exportPath ~/SimulatorRuntimes/
> xcodebuild -importPlatform "/Users/runner/SimulatorRuntimes/iphonesimulator_18.2_22C150.dmg"
> ```
> 
> This works but is quite fragile. You could improve this by extracting the path from the output of the first command. This is like 8Gb so that sucks to download each time, cache only allows a total of 10Gb so that would leave only 2Gb for other caches.

Same problem here, only this approach worked for me.

 ```
      - name: Manually download iOS 18.2
        if: env.simulator_cached == 'false'
        run: |
          xcodebuild -downloadPlatform iOS -buildVersion 18.2 -exportPath ~/SimulatorRuntimes/
          xcodebuild -importPlatform "/Users/runner/SimulatorRuntimes/iphonesimulator_18.2_22C150.dmg"
```

**Comment by justSmK** [comment]
I see this as a GitHub Runner issue. ['macos-15-arm64' has an iOS 18.2 simulator installed](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md#installed-simulators), while [`macos-14-arm64' does not](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md#installed-simulators).

**Comment by dejanskledar** [comment]
It appears, setting `macos-15` is not 100% resolving the issue, still just randomly got the same issue 🤔

**Comment by akshatjain-beam** [comment]
Hello, wanted to follow up regarding any updates on this? I am facing the same issue, and was wondering if i can get some help regarding how to fix it.

My workflow file - 
```
name: Daily iOS

on:
  schedule:
    - cron: "30 5 * * 1,3,5" # every Monday, Wednesday, Friday at 5:30 AM
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'

      - name: Check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2"
          channel: "stable"
          cache: true

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Install CocoaPods dependencies
        run: |
          pushd ios && pod install --repo-update && popd

      - name: Build Flutter iOS app
        run: |
          flutter build ipa --release -t lib/main_staging.dart --flavor stag --no-codesign
```
