### ISSUE TITLE
Xcode 16.3 is not available to run on the macos-latest

### ISSUE THREAD

**Issue by nikitakh-sure** [maxim-lobanov/setup-xcode#91]
hi there,

i am using the Xcode 16.3, the latest stable version available for everyone today
tried to update the `build and test` github action to migrate to Xcode 16.3, as i am using swift-5.9 latest compiler features
changing the `xcode-version` to the `16.3.0` does not work 

the entire log from failed github action

<img width="1050" alt="Image" src="https://github.com/user-attachments/assets/edac736c-b7e3-48aa-8c8c-3acd31ca61e5" />

test.yml code:

```yml
name: build & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: build, then test on the first available iPhone simulator
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.3.0'

      - name: run unit tests
        run: make test-ci
```
